# 1. Load and Explore Dataset

In [552]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [553]:
import pandas as pd
import numpy as np

In [554]:
df_train = pd.read_csv('../data/raw/train.csv')
df_test = pd.read_csv('../data/raw/test.csv')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_29604\779635099.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv('../data/raw/train.csv')

In [555]:
pd.set_option('display.max_columns', None)
df_train.head()

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,yr,ht,num,porpag,adjoe,pfr,year,type,Rec_Rank,ast_tov,rimmade,rimmade_rimmiss,midmade,midmade_midmiss,rim_ratio,mid_ratio,dunksmade,dunksmiss_dunksmade,dunks_ratio,pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id,drafted
0,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,1.6,4.6,15.8,16.3,10,14,0.714,26,68,0.382,13,39,0.333,0.3,1.5,13.1,So,2-Jun,NaN,0.258086,89.3938,2.5,2009,all,NaN,1.823646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.321,108.527,0.893017,49.9644,-4.995140,-1.623360,-3.371780,-4.723150,14.5769,-2.781990,-1.941150,0.1923,0.6154,0.8077,1.1923,0.3462,0.0385,3.8846,7be2aead-da4e-4d13-a74b-4c1e692e2368,0.0
1,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,3.8,6.3,13.6,19.8,30,45,0.667,56,113,0.496,20,51,0.392,1.0,1.1,27.4,So,4-Jun,NaN,1.334920,100.0660,3.4,2009,all,NaN,1.631621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.078,104.017,1.880030,111.9290,0.593024,1.385490,-0.792469,-0.300196,24.5294,-0.052263,-0.247934,0.6765,1.2647,1.9412,1.8235,0.4118,0.2353,5.9412,61de55d9-1582-4ea4-b593-44f6aa6524a6,0.0
2,South Florida,BE,27,72.0,96.2,21.8,45.7,47.98,2.1,8.0,14.7,15.9,45,67,0.672,67,157,0.427,50,154,0.325,0.0,0.9,21.5,Sr,4-Jun,NaN,2.274070,104.1070,1.7,2009,all,NaN,1.081662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.556,102.154,2.763870,115.0210,0.003161,1.024770,-1.021610,0.665065,33.1852,1.548230,-0.883163,0.6296,2.3333,2.9630,1.9630,0.4815,0.0000,12.1852,efdc4cfc-9dd0-4bf8-acef-7273e4d5b655,0.0
3,Pepperdine,WCC,30,44.5,97.7,16.0,53.6,53.69,4.1,9.4,13.7,23.8,14,27,0.519,25,63,0.397,28,62,0.452,0.8,1.9,21.6,Sr,4-Jun,NaN,0.552857,93.2086,2.0,2009,all,NaN,0.942830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.858,106.556,1.218710,84.1698,-0.977798,-0.502574,-0.475224,-0.736233,17.9667,-0.342775,-0.393459,0.7000,1.4333,2.1333,1.1000,0.5667,0.1333,4.9333,14f05660-bb3c-4868-b3dd-09bcdb64279d,0.0
4,Pacific,BW,33,56.2,96.5,22.0,52.8,54.31,8.3,18.6,8.2,22.7,64,114,0.561,93,176,0.528,0,0,0.000,1.9,1.3,64.8,Sr,8-Jun,NaN,1.060130,97.8554,3.8,2009,all,NaN,0.491229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.052,100.724,1.992790,128.0280,-1.836060,-1.946040,0.109983,-2.353180,22.9091,-1.684860,-0.668318,1.4242,3.3030,4.7273,0.8485,0.4545,0.3333,7.5758,a58db52f-fbba-4e7b-83d0-371efcfed039,0.0

In [556]:
df_test.head()

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,yr,ht,num,porpag,adjoe,pfr,year,type,Rec_Rank,ast_tov,rimmade,rimmade_rimmiss,midmade,midmade_midmiss,rim_ratio,mid_ratio,dunksmade,dunksmiss_dunksmade,dunks_ratio,pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id
0,Morgan St.,MEAC,2,3.0,115.1,4.7,50.0,50.00,0.0,4.6,0.0,0.0,0,0,0.000,0,0,0.000,1,3,0.333,0.0,0.0,0.0,Sr,4-Jun,25.0,0.261536,91.8097,3.5,2021,all,NaN,0.000000,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,106.4190,110.8410,0.655018,3.04099,-6.329190,-2.48656,-3.842620,-4.743390,10.0000,-2.467740,-2.275660,0.0000,0.3333,0.3333,0.0000,0.0000,0.0000,1.0000,cf302b4d-84f7-4124-a25d-a75eed31978b
1,South Carolina St.,MEAC,11,17.6,61.1,18.6,34.7,35.18,2.5,15.7,8.1,30.4,1,2,0.500,2,8,0.250,7,28,0.250,0.0,0.9,5.6,Sr,Jun-00,0.0,-1.110000,57.5491,2.8,2021,all,NaN,0.384583,2.0,4.0,0.0,4.0,0.5000,0.0000,0.0,0.0,NaN,NaN,110.1920,116.0180,0.450228,21.52420,-11.237600,-7.65745,-3.580200,-11.907200,11.5455,-7.494720,-4.412530,0.2727,1.4545,1.7273,0.4545,0.1818,0.0000,2.3636,f91837cd-4f49-4b70-963d-aeb82c6ce3da
2,Binghamton,AE,9,28.6,91.9,23.8,54.1,52.49,6.4,22.5,10.0,21.9,14,32,0.438,33,59,0.559,0,2,0.000,9.0,1.7,52.5,Sr,9-Jun,32.0,0.662985,93.6716,5.5,2021,all,NaN,0.500000,26.0,37.0,7.0,22.0,0.7027,0.3182,9.0,10.0,0.9,NaN,99.2886,105.5980,1.706130,48.26240,-0.796603,-3.88882,3.092220,-1.207060,23.3333,-2.924950,1.717890,1.3333,4.4444,5.7778,1.0000,0.6667,1.8889,8.8889,53ec2a29-1e7d-4c6d-86d7-d60d02af8916
3,Illinois,B10,7,1.3,111.0,10.4,83.3,83.33,0.0,13.4,0.0,33.6,0,0,0.000,1,2,0.500,1,1,1.000,0.0,0.0,0.0,Sr,2-Jun,32.0,0.135373,102.3240,5.0,2021,all,NaN,0.000000,0.0,0.0,1.0,2.0,NaN,0.5000,0.0,0.0,NaN,NaN,100.4870,95.3504,0.253055,2.53301,-1.802590,-1.15052,-0.652075,0.194558,2.2857,-0.767911,0.962469,0.0000,0.2857,0.2857,0.0000,0.0000,0.0000,0.7143,32402798-471c-4a54-8cb4-29cd95199014
4,Iowa St.,B12,23,78.5,103.1,21.5,54.0,56.12,3.6,10.2,7.8,16.1,31,36,0.861,62,129,0.481,58,147,0.395,0.3,1.4,13.0,Sr,4-Jun,5.0,2.977030,111.4260,3.5,2021,all,92.8,0.586950,14.0,26.0,48.0,103.0,0.5385,0.4660,0.0,0.0,NaN,NaN,111.7920,104.3060,2.610670,114.53100,1.064440,2.41992,-1.355480,1.874610,32.7826,2.893610,-1.019000,1.0435,2.8696,3.9130,1.1739,0.8261,0.0870,14.3043,73b960f9-27b8-4431-9d23-a760e9bbc360

In [557]:
df_train.shape

(56091, 64)

In [558]:
df_test.shape

(4970, 63)

In [559]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56091 entries, 0 to 56090
Data columns (total 64 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   team                 56091 non-null  object
 1   conf                 56091 non-null  object
 2   GP                   56091 non-null  int64
 3   Min_per              56091 non-null  float64
 4   Ortg                 56091 non-null  float64
 5   usg                  56091 non-null  float64
 6   eFG                  56091 non-null  float64
 7   TS_per               56091 non-null  float64
 8   ORB_per              56091 non-null  float64
 9   DRB_per              56091 non-null  float64
 10  AST_per              56091 non-null  float64
 11  TO_per               56091 non-null  float64
 12  FTM                  56091 non-null  int64
 13  FTA                  56091 non-null  int64
 14  FT_per               56091 non-null  float64
 15  twoPM                56091 non-null  int64
 16  twoPA                56091 non-null  int64
 17  twoP_per             56091 non-null  float64
 18  TPM                  56091 non-null  int64
 19  TPA                  56091 non-null  int64
 20  TP_per               56091 non-null  float64
 21  blk_per              56091 non-null  float64
 22  stl_per              56091 non-null  float64
 23  ftr                  56091 non-null  float64
 24  yr                   55799 non-null  object
 25  ht                   55993 non-null  object
 26  num                  51401 non-null  object
 27  porpag               56091 non-null  float64
 28  adjoe                56091 non-null  float64
 29  pfr                  56091 non-null  float64
 30  year                 56091 non-null  int64
 31  type                 56091 non-null  object
 32  Rec_Rank             17036 non-null  float64
 33  ast_tov              51901 non-null  float64
 34  rimmade              50010 non-null  float64
 35  rimmade_rimmiss      50010 non-null  float64
 36  midmade              50010 non-null  float64
 37  midmade_midmiss      50010 non-null  float64
 38  rim_ratio            46627 non-null  float64
 39  mid_ratio            46403 non-null  float64
 40  dunksmade            50010 non-null  float64
 41  dunksmiss_dunksmade  50010 non-null  float64
 42  dunks_ratio          25298 non-null  float64
 43  pick                 1386 non-null   float64
 44  drtg                 56047 non-null  float64
 45  adrtg                56047 non-null  float64
 46  dporpag              56047 non-null  float64
 47  stops                56047 non-null  float64
 48  bpm                  56047 non-null  float64
 49  obpm                 56047 non-null  float64
 50  dbpm                 56047 non-null  float64
 51  gbpm                 56047 non-null  float64
 52  mp                   56053 non-null  float64
 53  ogbpm                56047 non-null  float64
 54  dgbpm                56047 non-null  float64
 55  oreb                 56053 non-null  float64
 56  dreb                 56053 non-null  float64
 57  treb                 56053 non-null  float64
 58  ast                  56053 non-null  float64
 59  stl                  56053 non-null  float64
 60  blk                  56053 non-null  float64
 61  pts                  56053 non-null  float64
 62  player_id            56091 non-null  object
 63  drafted              56091 non-null  float64
dtypes: float64(49), int64(8), object(7)
memory usage: 27.4+ MB

In [560]:
df_train.describe(include = 'all')

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,yr,ht,num,porpag,adjoe,pfr,year,type,Rec_Rank,ast_tov,rimmade,rimmade_rimmiss,midmade,midmade_midmiss,rim_ratio,mid_ratio,dunksmade,dunksmiss_dunksmade,dunks_ratio,pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id,drafted
count,56091,56091,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,56091.000000,55799,55993,51401.0,56091.000000,56091.000000,56091.000000,56091.000000,56091,17036.000000,51901.000000,50010.000000,50010.000000,50010.000000,50010.000000,46627.000000,46403.000000,50010.000000,50010.000000,25298.000000,1386.000000,56047.000000,56047.000000,56047.000000,56047.000000,56047.000000,56047.000000,56047.000000,56047.000000,56053.000000,56047.000000,56047.000000,56053.000000,56053.000000,56053.000000,56053.000000,56053.000000,56053.000000,56053.000000,56091,56091.000000
unique,358,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,38,80.0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23929,NaN
top,Army,ACC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jr,7-Jun,1.0,NaN,NaN,NaN,NaN,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06dc8dc2-888e-4941-9106-4798cddfb9d2,NaN
freq,209,2297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14923,5578,2328.0,NaN,NaN,NaN,NaN,56091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN
mean,NaN,NaN,23.411973,37.325229,91.858295,18.149265,44.575513,47.676882,5.575376,12.673716,10.848740,20.337819,32.926708,47.152627,0.579696,41.412401,85.319160,0.426941,15.677613,45.616480,0.227449,1.876426,1.715305,37.437150,NaN,NaN,NaN,0.775720,89.328297,4.242936,2014.536557,NaN,53.456363,0.932305,28.066087,47.052490,14.494741,40.523115,0.564080,0.323633,3.836553,4.311618,0.863570,33.254690,103.319021,103.476636,1.438807,82.827595,-2.525068,-1.896939,-0.628129,-2.525672,16.973259,-2.083375,-0.442297,0.770611,1.892593,2.663204,1.073038,0.529475,0.282825,5.775381,NaN,0.009556
std,NaN,NaN,10.090542,28.061897,30.538819,6.204489,18.213813,17.414133,9.480239,10.878099,9.356001,12.226129,36.870041,49.557538,0.268678,43.730858,85.130054,0.193498,21.584619,58.060609,0.190430,5.876399,2.080477,36.813143,NaN,NaN,NaN,1.333574,30.923798,4.610406,3.450911,NaN,27.641745,0.696625,30.144876,47.582825,17.538837,44.401559,0.190824,0.171453,7.943541,8.709568,0.230396,16.651343,10.163752,11.033215,1.064868,65.344533,7.586977,5.184468,4.280805,8.304955,10.623801,6.190166,3.279438,0.738899,1.479148,2.099913,1.171148,0.469152,0.417754,4.953723,NaN,0.097287
min,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,-6.792410,-39.021300,0.000000,2009.000000,NaN,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-1330.060000,-1292.020000,-0.857238,0.043033,-102.186000,-92.593500,-57.459400,-242.523000,0.000000,-141.539000,-100.984000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,NaN,NaN,16.000000,9.500000,84.100000,14.500000,40.100000,43.930000,1.800000,8.400000,4.600000,14.800000,4.000000,7.000000,0.500000,5.000000,13.000000,0.375000,0.000000,1.000000,0.000000,0.000000,0.900000,19.400000,NaN,NaN,NaN,-0.170944,79.383600,2.800000,2012.000000,NaN,30.600000,0.459428,4.000000,8.000000,2.000000,6.000000,0.500000,0.250000,0.000000,0.000000,0.818200,20.000000,99.013850,98.083800,0.525770,19.846900,-5.377530,-3.986970,-2.285125,-5.379030,7.307700,-4.426515,-1.728030,0.225800,0.700000,1.000000,0.222200,0.160000,0.000000,1.571400,NaN,0.000000
50%,NaN,NaN,28.000000,35.900000,97.100000,18.100000,47.700000,50.850000,4.300000,11.900000,9.100000,19.100000,20.000000,31.000000,0.660000,27.000000,60.000000,0.460000,5.000000,18.000000,0.275000,0.800000,1.500000,32.800000,NaN,NaN,NaN,0.390392,94.648900,3.800000,2015.000000,NaN,55.400000,0.822562,18.000000,33.000000,8.000000,25.000000,0.580600,0.333300,0.000000,1.000000,1.000000,34.000000,103.671000,103.827000,1.266370,76.607600,-1.817550,-1.333140,-0.576564,-1.788120,16.714300,-1.580380,-0.313051,0.545500,1.633300,2.259300,0.677400,0.424200,0.133300,4.482800,NaN,0.000000
75%,NaN,NaN,31.000000,62.200000,106.900000,21.800000,53.200000,56.060000,8.100000,16.000000,15.100000,24.500000,50.000000,72.000000,0.755000,65.000000,134.000000,0.525000,25.000000,75.000000,0.357000,2.500000,2.200000,47.800000,NaN,NaN,NaN,1.485165,106.589000,5.200000,2018.000000,NaN,77.400000,1.263175,43.000000,73.000000,21.000000,61.000000,0.666700,0.402000,4.000000,5.000000,1.000000,48.000000,108.258500,109.315500,2.170135,134.975000,1.403830,1.013650,1.124280,1.399405,26.314300,0.992335,1.066415,1.111100,2.758600,3.833300,1.533300,0.793100,0.366700,9.069000,NaN,0.000000
max,NaN,NaN,41.000000,98.000000,834.000000,50.000000,150.000000,150.000000,1576.600000,1385.000000,100.000000,100.000000,312.000000,374.000000,1.000000,333.000000,678.000000,1.000000,147.000000,394.000000,1.000000,1072.000000,128.300000,1000.000000,NaN,NaN,NaN,8.658190,678.942000,720.000000,2020.000000,NaN,100.000000,14.007605,247.000000,358.000000,222.000000,532.000000,1.000000,1.000000,122.000000,132.000000,1.000000,60.000000,131.461000,144.685000,5.800530,360.572000,685.313000,161.995000,523.319000,269.508000,50.000000,225.485000,78.985500,5.933300,11.545500,14.533300,10.000000,4.000000,5.258100,30.090900,NaN,1.000000

In [561]:
data = {'team': (df_train['team'].nunique()), 'conf' : (df_train['conf'].nunique()), 'ht' : (df_train['ht'].nunique()), 'yr' : (df_train['yr'].nunique()), 
        'type' : (df_train['type'].nunique()), 'rec_rank' : (df_train['Rec_Rank'].nunique()),'conf' : (df_train['conf'].nunique())}

sample = pd.DataFrame(data, index = [1])
sample

   team  conf  ht  yr  type  rec_rank
1   358    36  38   7     1       500

# 2. Prepare data

In [562]:
df_train_cleaned = df_train.copy()
df_test_cleaned = df_test.copy()

Dropping columns from dataset because of excessive missing values

In [563]:
df_train_cleaned = df_train_cleaned.drop(['Rec_Rank', 'pick', 'dunks_ratio'], axis = 1 )
df_test_cleaned = df_test_cleaned.drop(['Rec_Rank', 'pick', 'dunks_ratio'], axis = 1)

Dropping columns because the range of categorical data is too high to encode into numbers or irrelevant

In [564]:
df_train_cleaned = df_train_cleaned.drop(['team', 'conf', 'ht', 'yr', 'type','num', 'player_id'], axis = 1 )
df_test_cleaned = df_test_cleaned.drop(['team', 'conf', 'ht', 'yr', 'type', 'num'], axis = 1)

In [565]:
df_train_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56091 entries, 0 to 56090
Data columns (total 54 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GP                   56091 non-null  int64
 1   Min_per              56091 non-null  float64
 2   Ortg                 56091 non-null  float64
 3   usg                  56091 non-null  float64
 4   eFG                  56091 non-null  float64
 5   TS_per               56091 non-null  float64
 6   ORB_per              56091 non-null  float64
 7   DRB_per              56091 non-null  float64
 8   AST_per              56091 non-null  float64
 9   TO_per               56091 non-null  float64
 10  FTM                  56091 non-null  int64
 11  FTA                  56091 non-null  int64
 12  FT_per               56091 non-null  float64
 13  twoPM                56091 non-null  int64
 14  twoPA                56091 non-null  int64
 15  twoP_per             56091 non-null  float64
 16  TPM                  56091 non-null  int64
 17  TPA                  56091 non-null  int64
 18  TP_per               56091 non-null  float64
 19  blk_per              56091 non-null  float64
 20  stl_per              56091 non-null  float64
 21  ftr                  56091 non-null  float64
 22  porpag               56091 non-null  float64
 23  adjoe                56091 non-null  float64
 24  pfr                  56091 non-null  float64
 25  year                 56091 non-null  int64
 26  ast_tov              51901 non-null  float64
 27  rimmade              50010 non-null  float64
 28  rimmade_rimmiss      50010 non-null  float64
 29  midmade              50010 non-null  float64
 30  midmade_midmiss      50010 non-null  float64
 31  rim_ratio            46627 non-null  float64
 32  mid_ratio            46403 non-null  float64
 33  dunksmade            50010 non-null  float64
 34  dunksmiss_dunksmade  50010 non-null  float64
 35  drtg                 56047 non-null  float64
 36  adrtg                56047 non-null  float64
 37  dporpag              56047 non-null  float64
 38  stops                56047 non-null  float64
 39  bpm                  56047 non-null  float64
 40  obpm                 56047 non-null  float64
 41  dbpm                 56047 non-null  float64
 42  gbpm                 56047 non-null  float64
 43  mp                   56053 non-null  float64
 44  ogbpm                56047 non-null  float64
 45  dgbpm                56047 non-null  float64
 46  oreb                 56053 non-null  float64
 47  dreb                 56053 non-null  float64
 48  treb                 56053 non-null  float64
 49  ast                  56053 non-null  float64
 50  stl                  56053 non-null  float64
 51  blk                  56053 non-null  float64
 52  pts                  56053 non-null  float64
 53  drafted              56091 non-null  float64
dtypes: float64(46), int64(8)
memory usage: 23.1 MB

In [566]:
print(df_train_cleaned.shape)
print(df_test_cleaned.shape)

(56091, 54)
(4970, 54)

Performing imputations on columns that have null values

In [567]:
for i in range(0,54):
    if df_train_cleaned.iloc[:, i].isna().sum() != 0:
        mean_value = df_train_cleaned.iloc[:, i].mean()
        df_train_cleaned.iloc[:, i].fillna(mean_value, inplace=True)
        
    if df_test_cleaned.iloc[:, i].isna().sum() != 0:
        mean_value = df_test_cleaned.iloc[:, i].mean()
        df_test_cleaned.iloc[:, i].fillna(mean_value, inplace=True)

Storing all the player ids from the Test data set

In [568]:
player_id = df_test_cleaned.pop('player_id')

In [569]:
df_train_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56091 entries, 0 to 56090
Data columns (total 54 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GP                   56091 non-null  int64
 1   Min_per              56091 non-null  float64
 2   Ortg                 56091 non-null  float64
 3   usg                  56091 non-null  float64
 4   eFG                  56091 non-null  float64
 5   TS_per               56091 non-null  float64
 6   ORB_per              56091 non-null  float64
 7   DRB_per              56091 non-null  float64
 8   AST_per              56091 non-null  float64
 9   TO_per               56091 non-null  float64
 10  FTM                  56091 non-null  int64
 11  FTA                  56091 non-null  int64
 12  FT_per               56091 non-null  float64
 13  twoPM                56091 non-null  int64
 14  twoPA                56091 non-null  int64
 15  twoP_per             56091 non-null  float64
 16  TPM                  56091 non-null  int64
 17  TPA                  56091 non-null  int64
 18  TP_per               56091 non-null  float64
 19  blk_per              56091 non-null  float64
 20  stl_per              56091 non-null  float64
 21  ftr                  56091 non-null  float64
 22  porpag               56091 non-null  float64
 23  adjoe                56091 non-null  float64
 24  pfr                  56091 non-null  float64
 25  year                 56091 non-null  int64
 26  ast_tov              56091 non-null  float64
 27  rimmade              56091 non-null  float64
 28  rimmade_rimmiss      56091 non-null  float64
 29  midmade              56091 non-null  float64
 30  midmade_midmiss      56091 non-null  float64
 31  rim_ratio            56091 non-null  float64
 32  mid_ratio            56091 non-null  float64
 33  dunksmade            56091 non-null  float64
 34  dunksmiss_dunksmade  56091 non-null  float64
 35  drtg                 56091 non-null  float64
 36  adrtg                56091 non-null  float64
 37  dporpag              56091 non-null  float64
 38  stops                56091 non-null  float64
 39  bpm                  56091 non-null  float64
 40  obpm                 56091 non-null  float64
 41  dbpm                 56091 non-null  float64
 42  gbpm                 56091 non-null  float64
 43  mp                   56091 non-null  float64
 44  ogbpm                56091 non-null  float64
 45  dgbpm                56091 non-null  float64
 46  oreb                 56091 non-null  float64
 47  dreb                 56091 non-null  float64
 48  treb                 56091 non-null  float64
 49  ast                  56091 non-null  float64
 50  stl                  56091 non-null  float64
 51  blk                  56091 non-null  float64
 52  pts                  56091 non-null  float64
 53  drafted              56091 non-null  float64
dtypes: float64(46), int64(8)
memory usage: 23.1 MB

In [571]:
df_train_cleaned

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,porpag,adjoe,pfr,year,ast_tov,rimmade,rimmade_rimmiss,midmade,midmade_midmiss,rim_ratio,mid_ratio,dunksmade,dunksmiss_dunksmade,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,drafted
0,26,29.5,97.3,16.6,42.5,44.43,1.6,4.6,15.8,16.3,10,14,0.714,26,68,0.382,13,39,0.333,0.3,1.5,13.1,0.258086,89.3938,2.5,2009,1.823646,28.066087,47.05249,14.494741,40.523115,0.56408,0.323633,3.836553,4.311618,108.321,108.5270,0.893017,49.964400,-4.995140,-1.623360,-3.371780,-4.723150,14.5769,-2.781990,-1.941150,0.1923,0.6154,0.8077,1.1923,0.3462,0.0385,3.8846,0.0
1,34,60.9,108.3,14.9,52.4,54.48,3.8,6.3,13.6,19.8,30,45,0.667,56,113,0.496,20,51,0.392,1.0,1.1,27.4,1.334920,100.0660,3.4,2009,1.631621,28.066087,47.05249,14.494741,40.523115,0.56408,0.323633,3.836553,4.311618,105.078,104.0170,1.880030,111.929000,0.593024,1.385490,-0.792469,-0.300196,24.5294,-0.052263,-0.247934,0.6765,1.2647,1.9412,1.8235,0.4118,0.2353,5.9412,0.0
2,27,72.0,96.2,21.8,45.7,47.98,2.1,8.0,14.7,15.9,45,67,0.672,67,157,0.427,50,154,0.325,0.0,0.9,21.5,2.274070,104.1070,1.7,2009,1.081662,28.066087,47.05249,14.494741,40.523115,0.56408,0.323633,3.836553,4.311618,107.556,102.1540,2.763870,115.021000,0.003161,1.024770,-1.021610,0.665065,33.1852,1.548230,-0.883163,0.6296,2.3333,2.9630,1.9630,0.4815,0.0000,12.1852,0.0
3,30,44.5,97.7,16.0,53.6,53.69,4.1,9.4,13.7,23.8,14,27,0.519,25,63,0.397,28,62,0.452,0.8,1.9,21.6,0.552857,93.2086,2.0,2009,0.942830,28.066087,47.05249,14.494741,40.523115,0.56408,0.323633,3.836553,4.311618,108.858,106.5560,1.218710,84.169800,-0.977798,-0.502574,-0.475224,-0.736233,17.9667,-0.342775,-0.393459,0.7000,1.4333,2.1333,1.1000,0.5667,0.1333,4.9333,0.0
4,33,56.2,96.5,22.0,52.8,54.31,8.3,18.6,8.2,22.7,64,114,0.561,93,176,0.528,0,0,0.000,1.9,1.3,64.8,1.060130,97.8554,3.8,2009,0.491229,28.066087,47.05249,14.494741,40.523115,0.56408,0.323633,3.836553,4.311618,101.052,100.7240,1.992790,128.028000,-1.836060,-1.946040,0.109983,-2.353180,22.9091,-1.684860,-0.668318,1.4242,3.3030,4.7273,0.8485,0.4545,0.3333,7.5758,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56086,1,0.1,0.0,48.9,0.0,0.00,0.0,0.0,0.0,0.0,0,0,0.000,0,1,0.000,0,0,0.000,0.0,0.0,0.0,-0.414715,-34.1733,0.0,2020,0.932305,0.000000,0.00000,0.000000,1.000000,0.56408,0.000000,0.000000,0.000000,119.423,114.0410,0.046150,0.088249,-55.565300,-38.138100,-17.427300,-39.908400,1.0000,-22.468800,-17.439600,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0
56087,1,0.2,206.9,35.9,100.0,102.56,0.0,0.0,0.0,0.0,2,2,1.000,1,1,1.000,0,0,0.000,0.0,0.0,200.0,0.998677,229.2430,0.0,2020,0.932305,1.000000,1.00000,0.000000,0.000000,1.00000,0.323633,0.000000,0.000000,115.350,118.0420,0.064534,0.201875,12.155000,22.404000,-10.249100,45.075600,2.0000,35.683300,9.392350,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,4.0000,0.0
56088,1,0.6,48.5,28.9,0.0,52.63,0.0,15.9,0.0,52.9,2,4,0.500,0,0,0.000,0,0,0.000,0.0,0.0,0.0,-0.685731,57.1100,5.7,2020,0.000000,28.066087,47.05249,14.494741,40.523115,0.56408,0.323633,3.836553,4.311618,106.225,95.4569,0.774465,1.156220,-24.689500,-18.070200,-6.619320,-16.613300,7.0000,-13.372700,-3.240610,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,2.0000,0.0
56089,1,0.1,300.0,20.0,150.0,150.00,0.0,0.0,0.0,0.0,0,0,0.000,0,0,0.000,1,1,1.000,0.0,0.0,0.0,0.631560,267.3470,0.0,2020,0.932305,0.000000,0.00000,0.000000,0.000000,0.56408,0.323633,0.000000,0.000000,116.888,124.5250,0.009770,0.095737,22.796400,29.370100,-6.573660,110.785000,1.0000,94.422600,16.362500,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,3.0000,0.0
56090,19,21.9,55.0,16.4,24.5,30.60,0.6,7.2,9.1,26.1,11,18,0.611,7,23,0.304,3,24,0.125,0.0,1.5,38.3,-1.408220,51.5221,2.3,2020,0.764721,28.066087,47.05249,14.494741,40.523115,0.56408,0.323633,3.836553,4.311618,123.166,124.4350,0.121025,31.474200,-14.186600,-8.070490,-6.116090,-12.741700,12.7727,-7.806150,-4.935520,0.0455,0.9091,0.9545,0.5909,0.4091,0.0000,2.4091,0.0

In [575]:
df_train_cleaned.to_csv('../data/processed/df_train_cleaned.csv', index=True)
df_test_cleaned.to_csv('../data/processed/df_test_cleaned.csv', index=True)

# 3. Data Splitting

In [466]:
y_data = df_train_cleaned.pop('drafted')

In [518]:
X_data = df_train_cleaned.copy()
X_test = df_test_cleaned.copy()

In [468]:
from sklearn.model_selection import train_test_split

In [519]:
X_train, X_val, y_train, y_val = train_test_split(X_data, y_data, test_size=0.2, random_state=8)

# 4. Data Scaling/Standardising

In [470]:
from sklearn.preprocessing import StandardScaler

In [471]:
scaler = StandardScaler()

In [472]:
from joblib import dump
dump(scaler, '../models/scaler.joblib')

['../models/scaler.joblib']

In [520]:
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train))
X_val_scaled = pd.DataFrame(scaler.fit_transform(X_val))
X_test_scaled = pd.DataFrame(scaler.fit_transform(X_test))

In [474]:
X_train.to_csv('../data/processed/X_train_scaled.csv', index=False)
X_val.to_csv('../data/processed/X_val_scaled.csv', index=False)
X_test.to_csv('../data/processed/X_test_scaled.csv', index=False)
y_train.to_csv('../data/processed/y_train.csv', index=False)
y_val.to_csv('../data/processed/y_val.csv', index=False)

# 5. Applying PCA

In [475]:
from sklearn.decomposition import PCA

In [576]:
pca = PCA(.99)
dump(pca, '../models/pca.joblib')

['../models/pca.joblib']

In [500]:
pca.fit(X_train)

PCA(n_components=0.99)

In [501]:
pca.n_components_

15

In [535]:
X_train_pca = pca.transform(X_train)
X_val_pca = pca.transform(X_val)
X_test_pca = pca.transform(X_test)

# 6. Apply Polynomial Transformation

In [480]:
from sklearn.preprocessing import PolynomialFeatures

In [536]:
poly = PolynomialFeatures(2)

In [577]:
dump(poly, '../models/poly.joblib')

['../models/poly.joblib']

In [537]:
X_train_pca = poly.fit_transform(X_train_pca)

In [538]:
X_val_pca = poly.transform(X_val_pca)
X_test_pca = poly.transform(X_test_pca)

# 7. Train Logistic Regression Model

In [539]:
from sklearn.linear_model import LogisticRegression

In [540]:
reg = LogisticRegression()

In [541]:
clf = reg.fit(X_train_pca, y_train)

C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\mla-at1-ZQOfbsrG-py3.9\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [542]:
from joblib import dump

dump(reg,  '../models/log_reg.joblib')

['../models/log_reg.joblib']

In [543]:
y_train_preds = reg.predict(X_train_pca)
y_val_preds = reg.predict(X_val_pca)
y_test_preds = reg.predict(X_test_pca)

In [544]:
from sklearn.metrics import roc_auc_score

In [545]:
y_score_train = clf.predict_proba(X_train_pca)[:, 1]

In [546]:
roc_auc_score(y_train, y_score_train)

0.7957932221358512

In [547]:
y_score_val = clf.predict_proba(X_val_pca)[:, 1]

In [548]:
y_score_val

array([5.42595086e-002, 3.58556979e-003, 1.12602381e-001, ...,
       2.76751369e-206, 5.24877993e-005, 3.48185461e-029])

In [549]:
roc_auc_score(y_val, y_score_val)

0.825227803213933

In [550]:
y_score_test = clf.predict_proba(X_test_pca)[:, 1]
y_score_test

array([1.48072335e-08, 1.18017064e-05, 1.04388151e-02, ...,
       1.43287827e-33, 3.62625097e-33, 8.52605723e-09])

In [551]:
df_scores = pd.concat({'Player_id': player_id, 'drafted': pd.Series(y_score_test)}, axis = 1)
df_scores

                                 Player_id       drafted
0     cf302b4d-84f7-4124-a25d-a75eed31978b  1.480723e-08
1     f91837cd-4f49-4b70-963d-aeb82c6ce3da  1.180171e-05
2     53ec2a29-1e7d-4c6d-86d7-d60d02af8916  1.043882e-02
3     32402798-471c-4a54-8cb4-29cd95199014  1.165007e-15
4     73b960f9-27b8-4431-9d23-a760e9bbc360  5.288851e-04
...                                    ...           ...
4965  a25ee55f-02a3-4f8e-8194-a5f427e14e7c  6.033170e-20
4966  d0d9f45e-7b01-44b3-8d40-514ec338611d  7.819023e-22
4967  f8df22c4-1602-4fab-896d-8820951aae2f  1.432878e-33
4968  b791c69a-f769-4163-afda-051a6fd20a9d  3.626251e-33
4969  18b51f5d-4746-4121-88fd-c8d0a1399130  8.526057e-09

[4970 rows x 2 columns]